#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20LHWebPortal.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="20LHdb")]
	public partial class HangoutDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHangout(Hangout instance);
    partial void UpdateHangout(Hangout instance);
    partial void DeleteHangout(Hangout instance);
    #endregion
		
		public HangoutDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HangoutDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HangoutDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HangoutDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HangoutDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Hangout> Hangouts
		{
			get
			{
				return this.GetTable<Hangout>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hangout")]
	public partial class Hangout : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Description;
		
		private System.Nullable<System.DateTime> _Date;
		
		private string _UserCreator;
		
		private string _Location;
		
		private string _Address;
		
		private int _PartySize;
		
		private int _Duration;
		
		private string _ContactInfo;
		
		private bool _GenderRatio;
		
		private int _AttendeeCount;
		
		private int _MaleAttendingCount;
		
		private int _FemaleAttendingCount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnUserCreatorChanging(string value);
    partial void OnUserCreatorChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPartySizeChanging(int value);
    partial void OnPartySizeChanged();
    partial void OnDurationChanging(int value);
    partial void OnDurationChanged();
    partial void OnContactInfoChanging(string value);
    partial void OnContactInfoChanged();
    partial void OnGenderRatioChanging(bool value);
    partial void OnGenderRatioChanged();
    partial void OnAttendeeCountChanging(int value);
    partial void OnAttendeeCountChanged();
    partial void OnMaleAttendingCountChanging(int value);
    partial void OnMaleAttendingCountChanged();
    partial void OnFemaleAttendingCountChanging(int value);
    partial void OnFemaleAttendingCountChanged();
    #endregion
		
		public Hangout()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCreator", DbType="NVarChar(128)")]
		public string UserCreator
		{
			get
			{
				return this._UserCreator;
			}
			set
			{
				if ((this._UserCreator != value))
				{
					this.OnUserCreatorChanging(value);
					this.SendPropertyChanging();
					this._UserCreator = value;
					this.SendPropertyChanged("UserCreator");
					this.OnUserCreatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NVarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartySize", DbType="Int NOT NULL")]
		public int PartySize
		{
			get
			{
				return this._PartySize;
			}
			set
			{
				if ((this._PartySize != value))
				{
					this.OnPartySizeChanging(value);
					this.SendPropertyChanging();
					this._PartySize = value;
					this.SendPropertyChanged("PartySize");
					this.OnPartySizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="Int NOT NULL")]
		public int Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this.OnDurationChanging(value);
					this.SendPropertyChanging();
					this._Duration = value;
					this.SendPropertyChanged("Duration");
					this.OnDurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactInfo", DbType="NVarChar(50)")]
		public string ContactInfo
		{
			get
			{
				return this._ContactInfo;
			}
			set
			{
				if ((this._ContactInfo != value))
				{
					this.OnContactInfoChanging(value);
					this.SendPropertyChanging();
					this._ContactInfo = value;
					this.SendPropertyChanged("ContactInfo");
					this.OnContactInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderRatio", DbType="Bit NOT NULL")]
		public bool GenderRatio
		{
			get
			{
				return this._GenderRatio;
			}
			set
			{
				if ((this._GenderRatio != value))
				{
					this.OnGenderRatioChanging(value);
					this.SendPropertyChanging();
					this._GenderRatio = value;
					this.SendPropertyChanged("GenderRatio");
					this.OnGenderRatioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendeeCount", DbType="Int NOT NULL")]
		public int AttendeeCount
		{
			get
			{
				return this._AttendeeCount;
			}
			set
			{
				if ((this._AttendeeCount != value))
				{
					this.OnAttendeeCountChanging(value);
					this.SendPropertyChanging();
					this._AttendeeCount = value;
					this.SendPropertyChanged("AttendeeCount");
					this.OnAttendeeCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaleAttendingCount", DbType="Int NOT NULL")]
		public int MaleAttendingCount
		{
			get
			{
				return this._MaleAttendingCount;
			}
			set
			{
				if ((this._MaleAttendingCount != value))
				{
					this.OnMaleAttendingCountChanging(value);
					this.SendPropertyChanging();
					this._MaleAttendingCount = value;
					this.SendPropertyChanged("MaleAttendingCount");
					this.OnMaleAttendingCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FemaleAttendingCount", DbType="Int NOT NULL")]
		public int FemaleAttendingCount
		{
			get
			{
				return this._FemaleAttendingCount;
			}
			set
			{
				if ((this._FemaleAttendingCount != value))
				{
					this.OnFemaleAttendingCountChanging(value);
					this.SendPropertyChanging();
					this._FemaleAttendingCount = value;
					this.SendPropertyChanged("FemaleAttendingCount");
					this.OnFemaleAttendingCountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
