<?xml version="1.0" encoding="utf-8"?><Database Name="aspnet-20LHWebPortal-20150420113045" Class="HangoutDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDb)\v11.0;AttachDbFilename=|DataDirectory|\aspnet-20LHWebPortal-20150420113045.mdf;Initial Catalog=aspnet-20LHWebPortal-20150420113045;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Hangout" Member="Hangouts">
    <Type Name="Hangout">
      <Column Name="Id" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserCreator" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" CanBeNull="false" />
      <Column Name="Address" Type="System.String" CanBeNull="false" />
      <Column Name="PartySize" Type="System.Int32" CanBeNull="false" />
      <Column Name="Duration" Type="System.Int32" CanBeNull="false" />
      <Column Name="ContactInfo" Type="System.String" CanBeNull="false" />
      <Column Name="GenderRatio" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AttendeeCount" Type="System.Int32" CanBeNull="false" />
      <Column Name="MaleAttendingCount" Type="System.Int32" CanBeNull="false" />
      <Column Name="FemaleAttendingCount" Type="System.Int32" CanBeNull="false" />
    </Type>
  </Table>
</Database>